/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectId
 */
export interface ObjectId {
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    machineIdentifier?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    processIdentifier?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    counter?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    time?: number;
    /**
     * 
     * @type {Date}
     * @memberof ObjectId
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof ObjectId
     */
    timeSecond?: number;
}

export function ObjectIdFromJSON(json: any): ObjectId {
    return ObjectIdFromJSONTyped(json, false);
}

export function ObjectIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'machineIdentifier': !exists(json, 'machineIdentifier') ? undefined : json['machineIdentifier'],
        'processIdentifier': !exists(json, 'processIdentifier') ? undefined : json['processIdentifier'],
        'counter': !exists(json, 'counter') ? undefined : json['counter'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'timeSecond': !exists(json, 'timeSecond') ? undefined : json['timeSecond'],
    };
}

export function ObjectIdToJSON(value?: ObjectId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timestamp': value.timestamp,
        'machineIdentifier': value.machineIdentifier,
        'processIdentifier': value.processIdentifier,
        'counter': value.counter,
        'time': value.time,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'timeSecond': value.timeSecond,
    };
}


