/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ExerciseSummaryDTO,
    ExerciseSummaryDTOFromJSON,
    ExerciseSummaryDTOToJSON,
} from '../models';

export interface AddGymSessionRequest {
    runningDistanceInMiles?: number;
    durationInMinutes?: number;
    bearerAuth?: string;
}

export interface AddStravaCodeRequest {
    code?: string;
    bearerAuth?: string;
}

export interface GetExerciseSummaryRequest {
    bearerAuth?: string;
}

export interface GetStravaCallbackRequest {
    code?: string;
}

export interface GetStravaOAuthURLRequest {
    bearerAuth?: string;
}

export interface GetStravaStatusRequest {
    bearerAuth?: string;
}

/**
 * no description
 */
export class ExerciseApi extends runtime.BaseAPI {

    /**
     * Add gym session
     */
    async addGymSessionRaw(requestParameters: AddGymSessionRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.runningDistanceInMiles !== undefined) {
            queryParameters['runningDistanceInMiles'] = requestParameters.runningDistanceInMiles;
        }

        if (requestParameters.durationInMinutes !== undefined) {
            queryParameters['durationInMinutes'] = requestParameters.durationInMinutes;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.bearerAuth !== undefined && requestParameters.bearerAuth !== null) {
            headerParameters['bearerAuth'] = String(requestParameters.bearerAuth);
        }

        const response = await this.request({
            path: `/exercise/gym-session`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add gym session
     */
    async addGymSession(requestParameters: AddGymSessionRequest): Promise<void> {
        await this.addGymSessionRaw(requestParameters);
    }

    /**
     * add strava code
     */
    async addStravaCodeRaw(requestParameters: AddStravaCodeRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.code !== undefined) {
            queryParameters['code'] = requestParameters.code;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.bearerAuth !== undefined && requestParameters.bearerAuth !== null) {
            headerParameters['bearerAuth'] = String(requestParameters.bearerAuth);
        }

        const response = await this.request({
            path: `/exercise/strava`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * add strava code
     */
    async addStravaCode(requestParameters: AddStravaCodeRequest): Promise<void> {
        await this.addStravaCodeRaw(requestParameters);
    }

    /**
     * Getting exercise summary
     */
    async getExerciseSummaryRaw(requestParameters: GetExerciseSummaryRequest): Promise<runtime.ApiResponse<ExerciseSummaryDTO>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.bearerAuth !== undefined && requestParameters.bearerAuth !== null) {
            headerParameters['bearerAuth'] = String(requestParameters.bearerAuth);
        }

        const response = await this.request({
            path: `/exercise/exercise-summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ExerciseSummaryDTOFromJSON(jsonValue));
    }

    /**
     * Getting exercise summary
     */
    async getExerciseSummary(requestParameters: GetExerciseSummaryRequest): Promise<ExerciseSummaryDTO> {
        const response = await this.getExerciseSummaryRaw(requestParameters);
        return await response.value();
    }

    /**
     * Callback URL for OAuth for Strava API
     */
    async getStravaCallbackRaw(requestParameters: GetStravaCallbackRequest): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.code !== undefined) {
            queryParameters['code'] = requestParameters.code;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/exercise/strava-callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Callback URL for OAuth for Strava API
     */
    async getStravaCallback(requestParameters: GetStravaCallbackRequest): Promise<boolean> {
        const response = await this.getStravaCallbackRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get OAuth Strava URL for Authentication
     */
    async getStravaOAuthURLRaw(requestParameters: GetStravaOAuthURLRequest): Promise<runtime.ApiResponse<string>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.bearerAuth !== undefined && requestParameters.bearerAuth !== null) {
            headerParameters['bearerAuth'] = String(requestParameters.bearerAuth);
        }

        const response = await this.request({
            path: `/exercise/strava-oauth`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * Get OAuth Strava URL for Authentication
     */
    async getStravaOAuthURL(requestParameters: GetStravaOAuthURLRequest): Promise<string> {
        const response = await this.getStravaOAuthURLRaw(requestParameters);
        return await response.value();
    }

    /**
     * getStravaStatus
     */
    async getStravaStatusRaw(requestParameters: GetStravaStatusRequest): Promise<runtime.ApiResponse<boolean>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.bearerAuth !== undefined && requestParameters.bearerAuth !== null) {
            headerParameters['bearerAuth'] = String(requestParameters.bearerAuth);
        }

        const response = await this.request({
            path: `/exercise/strava-status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     * getStravaStatus
     */
    async getStravaStatus(requestParameters: GetStravaStatusRequest): Promise<boolean> {
        const response = await this.getStravaStatusRaw(requestParameters);
        return await response.value();
    }

}
